//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SparesTracker
{
    using System;
    using System.Collections.Generic;
    
    public sealed partial class Spares
    {
        public int id { get; set; }
        public string name { get; set; }
        public int warehouseId { get; set; }
        public int amount { get; set; }
    
        public Warehouses Warehouses { get; set; }
    }
}
